name: polyname
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - python=3.6
  - pandas
  - numpy
  - cirpy
  - pubchempy
  - pip
  - nltk
  - chemdataextractor
  - pip:
    - json
    - os
    - glob
    - re
    - sys
    - subprocess
    - string
    - itertools
    - dict2xml


