name: polyname
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pandas
  - numpy
  - cirpy
  - pubchempy
  - csv
  - itertools
  - pip
  - sys
  - os
  - re
  - string
  - nltk
  - chemdataextractor
  - subprocess
  - json
  - glob
  - pip:
    - tqdm
